# CSI3007_LAB_13_22MID0181
# DATE:12/09/2025

In [2]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# attributes of array

In [12]:
print(arr.ndim)

1


In [13]:
print(arr.size)

6


In [14]:
print(arr.shape)


(6,)


In [23]:
identity_matrix = np.eye(4)#eye function used to create identity matrix
print("Identity Matrix:\n", identity_matrix)

# Create a 4x4 matrix with the diagonal shifted up (k=1)
shifted_up = np.eye(4, k=1)
print("\nDiagonal shifted up (k=1):\n", shifted_up)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal shifted up (k=1):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [28]:
array= np.linspace(0,10,5)#end will include
print("array",array)
# Generate 5 numbers, but exclude the endpoint
no_endpoint = np.linspace(0, 10, 5, endpoint=False)
print("\n no end point:", no_endpoint)


array [ 0.   2.5  5.   7.5 10. ]

 no end point: [0. 2. 4. 6. 8.]


In [35]:
arr_1=np.linspace(1,10,7)#equally spaced 7 points
print(arr_1)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [39]:
arr_2=np.arange(0,10,2)#instead of looping 
print(arr_2)

[0 2 4 6 8]


In [47]:
arr_3=np.zeros(5)
print(arr_3)

[0. 0. 0. 0. 0.]


In [51]:
arr_4=np.zeros((3,4),dtype=int)#2-D array with 3 rows and 4 colums
print(arr_4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Generates an array of random floating-point numbers from a uniform distribution over the range

In [57]:
arr_1=np.random.rand(6)#randomly generate 6 random float numbers
print(arr_1)

[0.41298457 0.8978542  0.90432542 0.66361606 0.87460938 0.48498449]


In [56]:
arr_5=np.random.rand(3,5)
print(arr_5)

[[0.66121513 0.01105486 0.95789268 0.64663307 0.37724146]
 [0.24830097 0.82063148 0.01823852 0.01497106 0.25477754]
 [0.36009516 0.24106439 0.65260899 0.21027468 0.47156768]]


In [59]:
arr_6=np.ones(5)#create 1-D array with 5 ones
print(arr_6)

[1. 1. 1. 1. 1.]


In [60]:
arr_7=np.ones((5,6),dtype=int)#Create a 2D array of shape (5,6) with integer data type
print(arr_7)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [70]:
arr_8=np.indices((2,3))#returns an array or tuple of arrays that represent the indices of a grid with a specified shape
print(arr_8)

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


# vandermonde matrix

In [40]:
vander=np.vander(np.linspace(0,2,5),2)
print(vander)

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]


In [41]:
import numpy as np
x = np.array([1, 2, 3, 4])
# Generate the Vandermonde matrix
# Generate a Vandermonde matrix with a specified number of columns 
# Here, colums is 3, so we get powers of 2, 1, 0.
vandermonde_matrix= np.vander(x,3)
print("\nVandermonde matrix with 3 colums:")
print(vandermonde_matrix)


Vandermonde matrix with 3 colums:
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
